INSERT INTO measures (number, description, responsible, sectionId, orderIndex) VALUES
('40.11', 'Proximidade de áreas urbanas e/ou turísticas.', 'EE', 6, 61),
('40.12', 'Zonas de proteção do património.', 'EE', 6, 62),
('41', 'No caso se venha a revelar necessário recorrer a terras de empréstimo para a execução das obras, as terras deverão ser provenientes de locais legalmente autorizados. Devem ser respeitados os seguintes aspetos para a seleção dos locais de empréstimo:', 'EE', 6, 63),
('41.1', 'As terras de empréstimo devem ser provenientes de locais próximos do local de aplicação, para minimizar o transporte.', 'EE', 6, 64),
('41.2', 'As terras de empréstimo não devem ser provenientes de: terrenos situados em linhas de água, leitos e margens de massas de água', 'EE', 6, 65),
('41.3', 'Zonas ameaçadas por cheias.', 'EE', 6, 66),
('41.4', 'Zonas de infiltração elevada.', 'EE', 6, 67),
('41.5', 'Perímetros de proteção de captações de água.', 'EE', 6, 68),
('41.6', 'Áreas classificadas da RAN ou da REN.', 'EE', 6, 69),
('41.7', 'Áreas classificadas para a conservação da natureza.', 'EE', 6, 70),
('41.8', 'Outras áreas onde as operações de movimentação das terras possam afetar espécies de flora e de fauna protegidas por lei, nomeadamente sobreiros e/ou azinheiras.', 'EE', 6, 71),
('41.9', 'Locais sensíveis do ponto de vista geotécnico.', 'EE', 6, 72),
('41.10', 'Locais sensíveis do ponto de vista paisagístico.', 'EE', 6, 73),
('41.1', 'Áreas com ocupação agrícola.', 'EE', 6, 74),
('41.11', 'Área na proximidade de áreas urbanas e/ou turísticas.', 'EE', 6, 75),
('41.12', 'Zonas de proteção do património.', 'EE', 6, 76),
('41.13', 'No caso se venha a revelar necessário recorrer a terras de empréstimo para a execução das obras, as terras deverão ser provenientes de locais legalmente autorizados. Devem ser respeitados os seguintes aspetos para a seleção dos locais de empréstimo:', 'EE', 6, 77),
('42', 'Privilegiar o uso de caminhos já existentes para aceder aos locais da obra.', 'EE', 7, 78),
('43', 'Definir corredores de circulação, de forma a evitar a circulação indiscriminada nas áreas/terrenos adjacentes.', 'EE', 7, 79),
('44', 'Assegurar o correto cumprimento das normas de segurança e sinalização de obras na via pública, tendo em consideração a segurança e a minimização das perturbações na atividade das populações.', 'EE', 7, 80);