INSERT INTO measures (number, description, responsible, sectionId, orderIndex) VALUES
('31', 'Não utilizar solo vivo proveniente da decapagem que esteja contaminado com propágulos das espécies vegetais exóticas invasoras e assegurar o seu depósito, devidamente acondicionado ou colocado em níveis de profundidade superiores a 1 m.', 'EE | RAA', 5, 41),
('32', 'Em caso de ser necessário utilizar terra vegetal, terras de empréstimo e materiais inertes, a utilizar na construção dos novos acessos, enchimento de fundações e, eventuais, outras áreas, assegurar junto dos fornecedores que não provêm de áreas ou de stocks contaminadas por espécies vegetais exóticas invasoras ou estão isentos da presença dos respetivos propágulos/sementes das referidas espécies para que as mesmas não alterem a ecologia local e introduzam plantas invasoras.', 'EE | RAA', 5, 42),
('33', 'Os trabalhos de escavações e aterros devem ser iniciados logo que os solos estejam limpos, evitando repetição de ações sobre as mesmas áreas.', 'EE', 6, 43),
('34', 'A execução de escavações e aterros deve ser interrompida em períodos de elevada pluviosidade e devem ser tomadas as devidas precauções para assegurar a estabilidade dos taludes e evitar o respetivo deslizamento.', 'EE', 6, 44),
('35', 'Sempre que possível, utilizar os materiais provenientes das escavações como material de aterro, de modo a minimizar o volume de terras sobrantes (a transportar para fora da área de intervenção).', 'EE', 6, 45),
('36', 'Os produtos de escavação que não possam ser aproveitados, ou em excesso, devem ser armazenados em locais com características adequadas para depósito.', 'EE', 6, 46),
('37', 'Caso se verifique a existência de materiais de escavação com vestígios de contaminação, estes devem ser armazenados em locais que evitem a contaminação dos solos e das águas subterrâneas, por infiltração ou escoamento das águas pluviais, até esses materiais serem encaminhados para destino final adequado.', 'EE', 6, 47),
('38', 'Garantir o escoamento das linhas de água superficiais em todas as fases de obra.', 'EE', 6, 48),
('39', 'As terras sobrantes devem ser preferencialmente reutilizadas nos aterros previstos neste projeto ou no paisagismo, ou ainda utilizadas noutras obras (como subproduto). O envio das terras sobrantes para operador de gestão de resíduos deve ser feito em último recurso de modo a diminuir os impactes negativos relacionados com o transporte e deposição daquelas terras.', 'EE', 6, 49),
('40', 'Caso haja necessidade de levar a depósito terras sobrantes, este deverá ser efetuado em locais legalmente autorizados. A seleção dessas zonas de depósito deve excluir as seguintes áreas: áreas urbanas e/ou turísticas; Zonas de proteção do património:', 'EE', 6, 50),
('40.1', 'Áreas do domínio público hídrico.', 'EE', 6, 51),
('40.2', 'Áreas inundáveis.', 'EE', 6, 52),
('40.3', 'Zonas de proteção de águas subterrâneas (áreas de elevada infiltração).', 'EE', 6, 53),
('40.4', 'Perímetros de proteção de captações.', 'EE', 6, 54),
('40.5', 'Áreas classificadas da Reserva Agrícola Nacional (RAN) ou Reserva Ecológica Nacional (REN).', 'EE', 6, 55),
('40.6', 'Outras áreas com estatuto de proteção, nomeadamente no âmbito da conservação da natureza.', 'EE', 6, 56),
('40.7', 'Outras áreas onde possam ser afetadas espécies de flora e de fauna protegidas por lei, nomeadamente sobreiros e/ou azinheiras.', 'EE', 6, 57),
('40.8', 'Locais sensíveis do ponto de vista geotécnico.', 'EE', 6, 58),
('40.9', 'Locais sensíveis do ponto de vista paisagístico.', 'EE', 6, 59),
('40.10', 'Áreas de ocupação agrícola.', 'EE', 6, 60);