CREATE TABLE `photogrammetry_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`surveyId` int NOT NULL,
	`projectId` int NOT NULL,
	`status` enum('validating','queued','processing','completed','rejected','failed','cancelled') NOT NULL DEFAULT 'validating',
	`workerTaskUuid` varchar(100),
	`progress` int NOT NULL DEFAULT 0,
	`imageCount` int NOT NULL DEFAULT 0,
	`geolocatedCount` int NOT NULL DEFAULT 0,
	`nadirCount` int NOT NULL DEFAULT 0,
	`obliqueCount` int NOT NULL DEFAULT 0,
	`missingMetadataCount` int NOT NULL DEFAULT 0,
	`validationJson` text,
	`metricsJson` text,
	`optionsJson` text,
	`orthophotoFileKey` varchar(500),
	`orthophotoUrl` text,
	`tilesBaseKey` varchar(500),
	`tilesUrlTemplate` text,
	`dsmFileKey` varchar(500),
	`dsmUrl` text,
	`reportFileKey` varchar(500),
	`reportUrl` text,
	`outputBoundsJson` text,
	`outputCrs` varchar(100),
	`gsdCm` varchar(50),
	`reprojectionErrorPx` varchar(50),
	`errorMessage` text,
	`requestedBy` int NOT NULL,
	`startedAt` timestamp,
	`finishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `photogrammetry_jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `photogrammetry_jobs_survey_unique` UNIQUE(`surveyId`)
);
--> statement-breakpoint
CREATE INDEX `photogrammetry_jobs_project_status_idx` ON `photogrammetry_jobs` (`projectId`,`status`);