import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Lang = "pt" | "en";

// Full translation dictionary
const translations: Record<string, Record<Lang, string>> = {
  // ─── Navigation / Sidebar ───
  "Dashboard": { pt: "Dashboard", en: "Dashboard" },
  "Matriz": { pt: "Matriz", en: "Tracking Matrix" },
  "Planos": { pt: "Planos", en: "Monitoring Plans" },
  "Calendário": { pt: "Calendário", en: "Calendar" },
  "Timeline": { pt: "Timeline", en: "Timeline" },
  "RDCD": { pt: "RDCD", en: "RDCD Report" },
  "GAMMA": { pt: "GAMMA", en: "GAMMA" },
  "Administração": { pt: "Administração", en: "Administration" },
  "Workflow": { pt: "Workflow", en: "Workflow" },
  "Ficha Semanal": { pt: "Ficha Semanal", en: "Weekly Form" },
  "Fases": { pt: "Fases", en: "Phases" },
  "Gestão de Resíduos": { pt: "Gestão de Resíduos", en: "Waste Management" },
  "KPI's": { pt: "KPI's", en: "KPIs" },
  "Certificações": { pt: "Certificações", en: "Certifications" },
  "MIRR": { pt: "MIRR", en: "MIRR" },
  "Perfil": { pt: "Perfil", en: "Profile" },
  "Deixar Feedback": { pt: "Deixar Feedback", en: "Leave Feedback" },
  "Terminar Sessão": { pt: "Terminar Sessão", en: "Sign Out" },
  "PROJETO": { pt: "PROJETO", en: "PROJECT" },
  "Todos os Projetos": { pt: "Todos os Projetos", en: "All Projects" },

  // ─── Dashboard ───
  "Visão geral do cumprimento ambiental": { pt: "Visão geral do cumprimento ambiental", en: "Environmental compliance overview" },
  "Fichas Aprovadas": { pt: "Fichas Aprovadas", en: "Approved Forms" },
  "Em Revisão": { pt: "Em Revisão", en: "Under Review" },
  "Projetos Ativos": { pt: "Projetos Ativos", en: "Active Projects" },
  "Em Incumprimento": { pt: "Em Incumprimento", en: "Non-Compliant" },
  "Cumprimento por Projeto": { pt: "Cumprimento por Projeto", en: "Compliance by Project" },
  "Entregáveis & Prazos": { pt: "Entregáveis & Prazos", en: "Deliverables & Deadlines" },
  "Validados": { pt: "Validados", en: "Validated" },
  "Total Eventos": { pt: "Total Eventos", en: "Total Events" },
  "Atrasados": { pt: "Atrasados", en: "Overdue" },
  "Resumo Geral": { pt: "Resumo Geral", en: "General Summary" },
  "Total de Fichas": { pt: "Total de Fichas", en: "Total Forms" },
  "Taxa de Aprovação": { pt: "Taxa de Aprovação", en: "Approval Rate" },
  "Empresas Ativas": { pt: "Empresas Ativas", en: "Active Companies" },
  "Próximo RDCD": { pt: "Próximo RDCD", en: "Next RDCD" },
  "Actividade de Submissão": { pt: "Actividade de Submissão", en: "Submission Activity" },
  "Evolução Semanal": { pt: "Evolução Semanal", en: "Weekly Evolution" },
  "Evolução do Projeto": { pt: "Evolução do Projeto", en: "Project Evolution" },
  "Distribuição por Entidade Executante": { pt: "Distribuição por Entidade Executante", en: "Distribution by Contractor" },
  "Distribuição por Estado": { pt: "Distribuição por Estado", en: "Distribution by Status" },
  "No prazo": { pt: "No prazo", en: "On track" },
  "Em atraso": { pt: "Em atraso", en: "Overdue" },
  "Sem data": { pt: "Sem data", en: "No date" },

  // ─── Ficha Semanal ───
  "Nova Ficha": { pt: "Nova Ficha", en: "New Form" },
  "Rascunhos": { pt: "Rascunhos", en: "Drafts" },
  "Histórico": { pt: "Histórico", en: "History" },
  "Revisão": { pt: "Revisão", en: "Review" },
  "Submeter": { pt: "Submeter", en: "Submit" },
  "Resubmeter": { pt: "Resubmeter", en: "Resubmit" },
  "Guardar": { pt: "Guardar", en: "Save" },
  "Cancelar": { pt: "Cancelar", en: "Cancel" },
  "Eliminar": { pt: "Eliminar", en: "Delete" },
  "Editar": { pt: "Editar", en: "Edit" },
  "Adicionar": { pt: "Adicionar", en: "Add" },
  "Exportar": { pt: "Exportar", en: "Export" },
  "Importar": { pt: "Importar", en: "Import" },
  "Guardado com sucesso": { pt: "Guardado com sucesso", en: "Saved successfully" },
  "Ficha submetida com sucesso!": { pt: "Ficha submetida com sucesso!", en: "Form submitted successfully!" },
  "Selecione a semana": { pt: "Selecione a semana", en: "Select week" },
  "Iniciar Ficha": { pt: "Iniciar Ficha", en: "Start Form" },
  "Conforme": { pt: "Conforme", en: "Compliant" },
  "Não Conforme": { pt: "Não Conforme", en: "Non-Compliant" },
  "Implementado": { pt: "Implementado", en: "Implemented" },
  "Não Aplicável": { pt: "Não Aplicável", en: "Not Applicable" },
  "Observações": { pt: "Observações", en: "Observations" },
  "Responsável": { pt: "Responsável", en: "Responsible" },
  "Mostrar todas as fases": { pt: "Mostrar todas as fases", en: "Show all phases" },
  "Mostrar só fase atual": { pt: "Mostrar só fase atual", en: "Show current phase only" },
  "Fase atual": { pt: "Fase atual", en: "Current phase" },
  "A mostrar todas as fases": { pt: "A mostrar todas as fases", en: "Showing all phases" },
  "medidas": { pt: "medidas", en: "measures" },
  "Submetida — Aguarda Revisão": { pt: "Submetida — Aguarda Revisão", en: "Submitted — Awaiting Review" },

  // ─── Matriz ───
  "Visão Agregada por Empresa": { pt: "Visão Agregada por Empresa", en: "Aggregated View by Company" },
  "Cada linha representa uma empresa": { pt: "Cada linha representa uma empresa", en: "Each row represents a company" },
  "Entregue": { pt: "Entregue", en: "Delivered" },
  "Criada (Rascunho)": { pt: "Criada (Rascunho)", en: "Created (Draft)" },
  "Rejeitada": { pt: "Rejeitada", en: "Rejected" },
  "Sem ficha": { pt: "Sem ficha", en: "No form" },
  "Parcialmente entregue": { pt: "Parcialmente entregue", en: "Partially delivered" },

  // ─── Review ───
  "Fichas Pendentes de Revisão": { pt: "Fichas Pendentes de Revisão", en: "Forms Pending Review" },
  "Já Revistas": { pt: "Já Revistas", en: "Already Reviewed" },
  "Aprovar Ficha": { pt: "Aprovar Ficha", en: "Approve Form" },
  "Rejeitar Ficha": { pt: "Rejeitar Ficha", en: "Reject Form" },
  "Revisão submetida com sucesso": { pt: "Revisão submetida com sucesso", en: "Review submitted successfully" },
  "Não pode aprovar uma ficha que criou ou submeteu.": { pt: "Não pode aprovar uma ficha que criou ou submeteu.", en: "You cannot approve a form you created or submitted." },
  "Separação de funções: peça a outro revisor para avaliar esta ficha.": { pt: "Separação de funções: peça a outro revisor para avaliar esta ficha.", en: "Separation of duties: ask another reviewer to evaluate this form." },

  // ─── Admin ───
  "Empresas": { pt: "Empresas", en: "Companies" },
  "Utilizadores": { pt: "Utilizadores", en: "Users" },
  "Convites": { pt: "Convites", en: "Invitations" },
  "Melhorias": { pt: "Melhorias", en: "Improvements" },
  "Pedidos de Acesso": { pt: "Pedidos de Acesso", en: "Access Requests" },
  "Auditoria": { pt: "Auditoria", en: "Audit Log" },
  "Nova Empresa": { pt: "Nova Empresa", en: "New Company" },
  "Criar": { pt: "Criar", en: "Create" },
  "Nome completo": { pt: "Nome completo", en: "Full name" },
  "Sigla / Nome curto": { pt: "Sigla / Nome curto", en: "Abbreviation / Short name" },
  "Tipo": { pt: "Tipo", en: "Type" },
  "Estado": { pt: "Estado", en: "Status" },
  "Ativa": { pt: "Ativa", en: "Active" },
  "Inativa": { pt: "Inativa", en: "Inactive" },
  "Empresa atualizada": { pt: "Empresa atualizada", en: "Company updated" },
  "Empresa eliminada": { pt: "Empresa eliminada", en: "Company deleted" },
  "Convidar Utilizador": { pt: "Convidar Utilizador", en: "Invite User" },

  // ─── Workflow ───
  "Workflow do Projeto": { pt: "Workflow do Projeto", en: "Project Workflow" },
  "Notas do Projeto": { pt: "Notas do Projeto", en: "Project Notes" },
  "Adicionar Nota": { pt: "Adicionar Nota", en: "Add Note" },
  "Nenhuma nota adicional definida para este projeto.": { pt: "Nenhuma nota adicional definida para este projeto.", en: "No additional notes defined for this project." },

  // ─── Calendar ───
  "Prazo Regulatório de Submissão": { pt: "Prazo Regulatório de Submissão", en: "Regulatory Submission Deadline" },
  "Prazo Interno de Preparação": { pt: "Prazo Interno de Preparação", en: "Internal Preparation Deadline" },
  "Submetido": { pt: "Submetido", en: "Submitted" },
  "Validado pela Entidade": { pt: "Validado pela Entidade", en: "Validated by Entity" },
  "Elementos a Reportar": { pt: "Elementos a Reportar", en: "Reporting Elements" },

  // ─── Phases / Timeline ───
  "Pré-Licenciamento": { pt: "Pré-Licenciamento", en: "Pre-Licensing" },
  "Licenciamento": { pt: "Licenciamento", en: "Licensing" },
  "Pré-Construção": { pt: "Pré-Construção", en: "Pre-Construction" },
  "Preparação Prévia": { pt: "Preparação Prévia", en: "Prior Preparation" },
  "Execução da Obra": { pt: "Execução da Obra", en: "Construction Execution" },
  "Fase Final de Construção": { pt: "Fase Final de Construção", en: "Final Construction Phase" },
  "Final de Construção": { pt: "Final de Construção", en: "End of Construction" },
  "Exploração / Operação": { pt: "Exploração / Operação", en: "Operation" },
  "Desativação": { pt: "Desativação", en: "Decommissioning" },
  "Concluído": { pt: "Concluído", en: "Completed" },
  "Em Curso": { pt: "Em Curso", en: "In Progress" },
  "Pendente": { pt: "Pendente", en: "Pending" },

  // ─── KPI ───
  "Submeter Dados": { pt: "Submeter Dados", en: "Submit Data" },
  "Metas": { pt: "Metas", en: "Targets" },
  "Incidentes Ambientais": { pt: "Incidentes Ambientais", en: "Environmental Incidents" },
  "Trabalhadores": { pt: "Trabalhadores", en: "Workers" },
  "Energia e CO₂": { pt: "Energia e CO₂", en: "Energy & CO₂" },
  "Água": { pt: "Água", en: "Water" },
  "Semana": { pt: "Semana", en: "Week" },
  "Mês": { pt: "Mês", en: "Month" },
  "Semestre": { pt: "Semestre", en: "Semester" },
  "Ano": { pt: "Ano", en: "Year" },
  "Projeto": { pt: "Projeto", en: "Project" },

  // ─── RDCD ───
  "Definir Período": { pt: "Definir Período", en: "Define Period" },
  "Selecionar Medidas": { pt: "Selecionar Medidas", en: "Select Measures" },
  "Pré-visualização": { pt: "Pré-visualização", en: "Preview" },
  "Incluir Planos de Monitorização": { pt: "Incluir Planos de Monitorização", en: "Include Monitoring Plans" },
  "Gerar Relatório": { pt: "Gerar Relatório", en: "Generate Report" },

  // ─── Common ───
  "Carregar": { pt: "Carregar", en: "Upload" },
  "Descarregar": { pt: "Descarregar", en: "Download" },
  "Pesquisar": { pt: "Pesquisar", en: "Search" },
  "Filtrar": { pt: "Filtrar", en: "Filter" },
  "Todos": { pt: "Todos", en: "All" },
  "Nenhum resultado": { pt: "Nenhum resultado", en: "No results" },
  "A carregar...": { pt: "A carregar...", en: "Loading..." },
  "Erro": { pt: "Erro", en: "Error" },
  "Sucesso": { pt: "Sucesso", en: "Success" },
  "Confirmar": { pt: "Confirmar", en: "Confirm" },
  "Voltar": { pt: "Voltar", en: "Back" },
  "Fechar": { pt: "Fechar", en: "Close" },
  "Sim": { pt: "Sim", en: "Yes" },
  "Não": { pt: "Não", en: "No" },
  "Selecionar projeto": { pt: "Selecionar projeto", en: "Select project" },
  "Plataforma Ambiental — Start Campus": { pt: "Plataforma Ambiental — Start Campus", en: "Environmental Platform — Start Campus" },

  // ─── Login ───
  "Iniciar Sessão": { pt: "Iniciar Sessão", en: "Sign In" },
  "Email": { pt: "Email", en: "Email" },
  "Palavra-passe": { pt: "Palavra-passe", en: "Password" },
  "Entrar": { pt: "Entrar", en: "Sign In" },
  "Criar Conta": { pt: "Criar Conta", en: "Create Account" },
  "Esqueceu a palavra-passe?": { pt: "Esqueceu a palavra-passe?", en: "Forgot password?" },
  "Entrar com Autodesk": { pt: "Entrar com Autodesk", en: "Sign in with Autodesk" },

  // ─── Certifications ───
  "Próximos Prazos": { pt: "Próximos Prazos", en: "Upcoming Deadlines" },
  "Submissões": { pt: "Submissões", en: "Submissions" },

  // ─── GAMMA ───
  "Necessidades": { pt: "Necessidades", en: "Needs Assessment" },
  "Scorecard": { pt: "Scorecard", en: "Scorecard" },
  "Vencedores": { pt: "Vencedores", en: "Winners" },
  "Definições": { pt: "Definições", en: "Settings" },
  "Candidatura": { pt: "Candidatura", en: "Application" },
  // ─── Dashboard (individual project) ───
  "Visão geral do cumprimento ambiental": { pt: "Visão geral do cumprimento ambiental", en: "Environmental compliance overview" },
  "Todas as empresas": { pt: "Todas as empresas", en: "All companies" },
  "Todas as semanas": { pt: "Todas as semanas", en: "All weeks" },
  "Todos os estados": { pt: "Todos os estados", en: "All statuses" },
  "Todas as secções": { pt: "Todas as secções", en: "All sections" },
  "Próximo RDCD": { pt: "Próximo RDCD", en: "Next RDCD" },
  "Gerar RDCD": { pt: "Gerar RDCD", en: "Generate RDCD" },
  "Fase de Operação": { pt: "Fase de Operação", en: "Operation Phase" },
  "Próximos Reportings": { pt: "Próximos Reportings", en: "Upcoming Reports" },
  "Responsáveis pelo Reporting": { pt: "Responsáveis pelo Reporting", en: "Reporting Owners" },
  "Sem responsável": { pt: "Sem responsável", en: "No owner assigned" },
  // ─── KPI ───
  "Indicadores de sustentabilidade": { pt: "Indicadores de sustentabilidade", en: "Sustainability indicators" },
  "Exportar": { pt: "Exportar", en: "Export" },
  "Período": { pt: "Período", en: "Period" },
  "Semana": { pt: "Semana", en: "Week" },
  "Mês": { pt: "Mês", en: "Month" },
  "Semestre": { pt: "Semestre", en: "Semester" },
  "Ano": { pt: "Ano", en: "Year" },
  "Projeto": { pt: "Projeto", en: "Project" },
  "Energia & CO2": { pt: "Energia & CO2", en: "Energy & CO2" },
  "Água": { pt: "Água", en: "Water" },
  "Trabalhadores": { pt: "Trabalhadores", en: "Workers" },
  "Incidentes": { pt: "Incidentes", en: "Incidents" },
  "Incidentes Ambientais": { pt: "Incidentes Ambientais", en: "Environmental Incidents" },
  "Água Construção": { pt: "Água Construção", en: "Construction Water" },
  "Combustível Total": { pt: "Combustível Total", en: "Total Fuel" },
  "Eletricidade": { pt: "Eletricidade", en: "Electricity" },
  "Submeter": { pt: "Submeter", en: "Submit" },
  "Submeter dados": { pt: "Submeter dados", en: "Submit Data" },
  "Metas": { pt: "Metas", en: "Targets" },
  "Consumo Combustível (L)": { pt: "Consumo Combustível (L)", en: "Fuel Consumption (L)" },
  "Eletricidade (kWh)": { pt: "Eletricidade (kWh)", en: "Electricity (kWh)" },
  // ─── Common ───
  "Guardar": { pt: "Guardar", en: "Save" },
  "Cancelar": { pt: "Cancelar", en: "Cancel" },
  "Eliminar": { pt: "Eliminar", en: "Delete" },
  "Editar": { pt: "Editar", en: "Edit" },
  "Criar": { pt: "Criar", en: "Create" },
  "Fechar": { pt: "Fechar", en: "Close" },
  "Confirmar": { pt: "Confirmar", en: "Confirm" },
  "Voltar": { pt: "Voltar", en: "Back" },
  "Pesquisar": { pt: "Pesquisar", en: "Search" },
  "Sem dados": { pt: "Sem dados", en: "No data" },
  "Carregando...": { pt: "Carregando...", en: "Loading..." },
  "Sem ficha": { pt: "Sem ficha", en: "No form" },
  "Entregue": { pt: "Entregue", en: "Delivered" },
  "Em Revisão": { pt: "Em Revisão", en: "Under Review" },
  "Criada (Rascunho)": { pt: "Criada (Rascunho)", en: "Created (Draft)" },
  "Rejeitada": { pt: "Rejeitada", en: "Rejected" },
  "Parcialmente entregue": { pt: "Parcialmente entregue", en: "Partially delivered" },
// ─── Dashboard extended ───
  "Actividade de Submissão (últimas 12 semanas)": { pt: "Actividade de Submissão (últimas 12 semanas)", en: "Submission Activity (last 12 weeks)" },
  "Cumprimento por Secção": { pt: "Cumprimento por Secção", en: "Compliance by Section" },
  "Distribuição por Entidade Executante": { pt: "Distribuição por Entidade Executante", en: "Distribution by Contractor" },
  "Distribuição por Estado": { pt: "Distribuição por Estado", en: "Distribution by Status" },
  "Empresas Ativas": { pt: "Empresas Ativas", en: "Active Companies" },
  "Evolução Semanal": { pt: "Evolução Semanal", en: "Weekly Evolution" },
  "Evolução do Projeto (Acumulado)": { pt: "Evolução do Projeto (Acumulado)", en: "Project Evolution (Cumulative)" },
  "Implementado": { pt: "Implementado", en: "Implemented" },
  "Conforme": { pt: "Conforme", en: "Compliant" },
  "Não Conforme": { pt: "Não Conforme", en: "Non-Compliant" },
  "Não Aplicável": { pt: "Não Aplicável", en: "Not Applicable" },
  "Limpar": { pt: "Limpar", en: "Clear" },
  "Sem dados disponíveis": { pt: "Sem dados disponíveis", en: "No data available" },
  "No prazo": { pt: "No prazo", en: "On time" },
  "Sem data": { pt: "Sem data", en: "No date" },
  "Monitorização contínua de medidas ambientais e gestão de resíduos": { pt: "Monitorização contínua de medidas ambientais e gestão de resíduos", en: "Continuous monitoring of environmental measures and waste management" },
  // ─── KPI extended ───
  "Aberto": { pt: "Aberto", en: "Open" },
  "Alto": { pt: "Alto", en: "High" },
  "Baixo": { pt: "Baixo", en: "Low" },
  "Crítico": { pt: "Crítico", en: "Critical" },
  "Médio": { pt: "Médio", en: "Medium" },
  "Calculado": { pt: "Calculado", en: "Calculated" },
  "Atingir": { pt: "Atingir", en: "Target" },
  "Anual": { pt: "Anual", en: "Annual" },
  // ─── Calendario extended ───
  "Ação": { pt: "Ação", en: "Action" },
  "Ações": { pt: "Ações", en: "Actions" },
  "Categoria": { pt: "Categoria", en: "Category" },
  "Data Limite": { pt: "Data Limite", en: "Deadline" },
  "Data": { pt: "Data", en: "Date" },
  "Editar Evento": { pt: "Editar Evento", en: "Edit Event" },
  "Em Atraso": { pt: "Em Atraso", en: "Overdue" },
  "Gerir": { pt: "Gerir", en: "Manage" },
  "Novo Evento": { pt: "Novo Evento", en: "New Event" },
  "Hoje": { pt: "Hoje", en: "Today" },
  "Calendário de Reporting": { pt: "Calendário de Reporting", en: "Reporting Calendar" },
  "Datas de entrega de reportings": { pt: "Datas de entrega de reportings", en: "Reporting delivery dates" },
  "Legenda": { pt: "Legenda", en: "Legend" },
  "Prazo Regulatório de Submissão": { pt: "Prazo Regulatório de Submissão", en: "Regulatory Submission Deadline" },
  "Prazo Interno de Preparação": { pt: "Prazo Interno de Preparação", en: "Internal Preparation Deadline" },
  "Submetido": { pt: "Submetido", en: "Submitted" },
  "Validado pela Entidade": { pt: "Validado pela Entidade", en: "Validated by Authority" },
  // ─── WeeklyForm extended ───
  "Anexar ficheiro": { pt: "Anexar ficheiro", en: "Attach file" },
  "Aprovada": { pt: "Aprovada", en: "Approved" },
  "Selecionar Semana": { pt: "Selecionar Semana", en: "Select Week" },
  "Submetida — Aguarda Revisão": { pt: "Submetida — Aguarda Revisão", en: "Submitted — Awaiting Review" },
  // ─── ReviewPage ───
  "Empresa": { pt: "Empresa", en: "Company" },
  "Estado": { pt: "Estado", en: "Status" },
  "Fichas Já Revistas": { pt: "Fichas Já Revistas", en: "Already Reviewed Forms" },
  "Nenhuma ficha pendente de revisão": { pt: "Nenhuma ficha pendente de revisão", en: "No forms pending review" },
  "Notas gerais da revisão": { pt: "Notas gerais da revisão", en: "General review notes" },
  "Notas": { pt: "Notas", en: "Notes" },
  // ─── Timeline ───
  "Ciclo de vida dos projetos Start Campus": { pt: "Ciclo de vida dos projetos Start Campus", en: "Start Campus project lifecycle" },
  "Concluída": { pt: "Concluída", en: "Completed" },
  "Em Curso": { pt: "Em Curso", en: "In Progress" },
  "Pendente": { pt: "Pendente", en: "Pending" },
  "Operação": { pt: "Operação", en: "Operation" },
  "Progresso Global": { pt: "Progresso Global", en: "Overall Progress" },
  "Pipeline de Fases": { pt: "Pipeline de Fases", en: "Phase Pipeline" },
  "Detalhe por Fase": { pt: "Detalhe por Fase", en: "Detail by Phase" },
  "Vista Geral": { pt: "Vista Geral", en: "Overview" },
  // ─── Admin ───
  "Administrador": { pt: "Administrador", en: "Administrator" },
  "Aprovar": { pt: "Aprovar", en: "Approve" },
  "Rejeitar": { pt: "Rejeitar", en: "Reject" },
  "Empresas": { pt: "Empresas", en: "Companies" },
  "Utilizadores": { pt: "Utilizadores", en: "Users" },
  "Convites": { pt: "Convites", en: "Invitations" },
  "Auditoria": { pt: "Auditoria", en: "Audit Log" },
  "Melhorias": { pt: "Melhorias", en: "Improvements" },
  "Pedidos de Acesso": { pt: "Pedidos de Acesso", en: "Access Requests" },
  "Imagens": { pt: "Imagens", en: "Images" },
  // ─── Workflow ───
  "Decisão da RAA": { pt: "Decisão da RAA", en: "RAA Decision" },
  "Dono de Obra": { pt: "Dono de Obra", en: "Project Owner" },
  "Entidade Executante": { pt: "Entidade Executante", en: "Contractor" },
  // ─── Planos ───
  "Planos de Monitorização": { pt: "Planos de Monitorização", en: "Monitoring Plans" },
  "Criar Novo Plano": { pt: "Criar Novo Plano", en: "Create New Plan" },
  "Entrega este mês": { pt: "Entrega este mês", en: "Due this month" },
  // ─── RDCD ───
  "Compilação de Medidas": { pt: "Compilação de Medidas", en: "Measures Compilation" },
  "Definir Período": { pt: "Definir Período", en: "Set Period" },
  "Fichas analisadas": { pt: "Fichas analisadas", en: "Forms analyzed" },
  "Incluir Planos de Monitorização no RDCD": { pt: "Incluir Planos de Monitorização no RDCD", en: "Include Monitoring Plans in RDCD" },
  "Medidas no relatório": { pt: "Medidas no relatório", en: "Measures in report" },
  // ─── Auto-generated translations ───
  "A carregar matriz...": { pt: "A carregar matriz...", en: "Loading matrix..." },
  "Acesso restrito.": { pt: "Acesso restrito.", en: "Restricted access." },
  "Acesso restrito a Admin e Dono de Obra.": { pt: "Acesso restrito a Admin e Dono de Obra.", en: "Restricted to Admin and Project Owner." },
  "Adicionar Medida": { pt: "Adicionar Medida", en: "Add Measure" },
  "Ação imediata necessária": { pt: "Ação imediata necessária", en: "Immediate action required" },
  "AÇÃO IMEDIATA NECESSÁRIA": { pt: "AÇÃO IMEDIATA NECESSÁRIA", en: "IMMEDIATE ACTION REQUIRED" },
  "Cargo": { pt: "Cargo", en: "Position" },
  "Chave": { pt: "Chave", en: "Key" },
  "Código": { pt: "Código", en: "Code" },
  "Código LER": { pt: "Código LER", en: "LER Code" },
  "Comentário RAA:": { pt: "Comentário RAA:", en: "RAA Comment:" },
  "Confirma que o plano foi entregue à entidade competente?": { pt: "Confirma que o plano foi entregue à entidade competente?", en: "Confirm the plan was delivered to the competent authority?" },
  "Confirmar nova palavra-passe": { pt: "Confirmar nova palavra-passe", en: "Confirm new password" },
  "Consulte e exporte fichas por período ou por medida": { pt: "Consulte e exporte fichas por período ou por medida", en: "View and export forms by period or measure" },
  "Criar Novo Projeto": { pt: "Criar Novo Projeto", en: "Create New Project" },
  "Crie o primeiro projeto para começar.": { pt: "Crie o primeiro projeto para começar.", en: "Create the first project to get started." },
  "Cód. APA Receção": { pt: "Cód. APA Receção", en: "APA Reception Code" },
  "Cód. APA Transporte": { pt: "Cód. APA Transporte", en: "APA Transport Code" },
  "DCAPE — Acompanhamento Semanal": { pt: "DCAPE — Acompanhamento Semanal", en: "DCAPE — Weekly Monitoring" },
  "Data Fim": { pt: "Data Fim", en: "End Date" },
  "Data Início": { pt: "Data Início", en: "Start Date" },
  "Definições MIRR": { pt: "Definições MIRR", en: "MIRR Settings" },
  "Delivering Sustainable AI-Scale Data Centers": { pt: "Delivering Sustainable AI-Scale Data Centers", en: "Delivering Sustainable AI-Scale Data Centers" },
  "Descrição (opcional)": { pt: "Descrição (opcional)", en: "Description (optional)" },
  "Designação": { pt: "Designação", en: "Description" },
  "Destino": { pt: "Destino", en: "Destination" },
  "Destino Final": { pt: "Destino Final", en: "Final Destination" },
  "Disponível no Histórico": { pt: "Disponível no Histórico", en: "Available in History" },
  "EE/RAP corrige e resubmete": { pt: "EE/RAP corrige e resubmete", en: "EE/RAP corrects and resubmits" },
  "Edite o número, descrição ou elimine medidas desta fase. Apenas visível para administradores.": { pt: "Edite o número, descrição ou elimine medidas desta fase. Apenas visível para administradores.", en: "Edit the number, description or delete measures from this phase. Only visible to administrators." },
  "Eliminado por": { pt: "Eliminado por", en: "Deleted by" },
  "Empresa:": { pt: "Empresa:", en: "Company:" },
  "Entregue à entidade competente": { pt: "Entregue à entidade competente", en: "Delivered to competent authority" },
  "Escolha os projetos a incluir neste RDCD. Pode selecionar um, vários ou todos.": { pt: "Escolha os projetos a incluir neste RDCD. Pode selecionar um, vários ou todos.", en: "Choose projects to include in this RDCD. You can select one, several or all." },
  "Esta ficha foi rejeitada pela RAA e requer correção prioritária.": { pt: "Esta ficha foi rejeitada pela RAA e requer correção prioritária.", en: "This form was rejected by RAA and requires priority correction." },
  "Expirado": { pt: "Expirado", en: "Expired" },
  "Exportar Evolução por Medida": { pt: "Exportar Evolução por Medida", en: "Export Evolution by Measure" },
  "Exportável em PDF": { pt: "Exportável em PDF", en: "Exportable as PDF" },
  "Falta confirmar envio à entidade competente": { pt: "Falta confirmar envio à entidade competente", en: "Pending confirmation of delivery to competent authority" },
  "Ficha validada e arquivada no histórico": { pt: "Ficha validada e arquivada no histórico", en: "Form validated and archived in history" },
  "Filtrar por Estado": { pt: "Filtrar por Estado", en: "Filter by Status" },
  "Filtrar por:": { pt: "Filtrar por:", en: "Filter by:" },
  "Filtrar:": { pt: "Filtrar:", en: "Filter:" },
  "Fluxo de Submissão de Fichas": { pt: "Fluxo de Submissão de Fichas", en: "Form Submission Workflow" },
  "Gestão de Projetos": { pt: "Gestão de Projetos", en: "Project Management" },
  "Histórico de Submissões": { pt: "Histórico de Submissões", en: "Submission History" },
  "LER": { pt: "LER", en: "LER" },
  "Legenda:": { pt: "Legenda:", en: "Legend:" },
  "Link e-GAR": { pt: "Link e-GAR", en: "e-GAR Link" },
  "Marcadas:": { pt: "Marcadas:", en: "Marked:" },
  "Modo de visualização.": { pt: "Modo de visualização.", en: "View mode." },
  "N/A": { pt: "N/A", en: "N/A" },
  "Nenhum plano registado.": { pt: "Nenhum plano registado.", en: "No plans registered." },
  "Nenhum programa registado.": { pt: "Nenhum programa registado.", en: "No programmes registered." },
  "Nenhum projeto criado ainda.": { pt: "Nenhum projeto criado ainda.", en: "No projects created yet." },
  "Nenhum utilizador registado.": { pt: "Nenhum utilizador registado.", en: "No users registered." },
  "Nenhuma empresa registada.": { pt: "Nenhuma empresa registada.", en: "No companies registered." },
  "Nenhuma fase com medidas encontrada.": { pt: "Nenhuma fase com medidas encontrada.", en: "No phases with measures found." },
  "Nenhuma ficha aprovada encontrada no período selecionado. Verifique os projetos e semanas escolhidos.": { pt: "Nenhuma ficha aprovada encontrada no período selecionado. Verifique os projetos e semanas escolhidos.", en: "No approved forms found in the selected period. Check the projects and weeks chosen." },
  "Nenhuma ficha revista ainda": { pt: "Nenhuma ficha revista ainda", en: "No forms reviewed yet" },
  "Nenhuma medida com o estado selecionado": { pt: "Nenhuma medida com o estado selecionado", en: "No measures with the selected status" },
  "Nenhuma medida registada nesta fase.": { pt: "Nenhuma medida registada nesta fase.", en: "No measures registered in this phase." },
  "Nome": { pt: "Nome", en: "Name" },
  "Nome Completo": { pt: "Nome Completo", en: "Full Name" },
  "Nome de Perfil": { pt: "Nome de Perfil", en: "Profile Name" },
  "Notas do revisor:": { pt: "Notas do revisor:", en: "Reviewer notes:" },
  "Nova palavra-passe": { pt: "Nova palavra-passe", en: "New password" },
  "Novo Plano": { pt: "Novo Plano", en: "New Plan" },
  "Não pode aprovar/rejeitar uma ficha que criou ou submeteu.": { pt: "Não pode aprovar/rejeitar uma ficha que criou ou submeteu.", en: "You cannot approve/reject a form you created or submitted." },
  "Não tem acesso ao autenticador? Contacte": { pt: "Não tem acesso ao autenticador? Contacte", en: "Don't have access to authenticator? Contact" },
  "Ocultar fases, definir datas de início/fim (sincroniza com calendário)": { pt: "Ocultar fases, definir datas de início/fim (sincroniza com calendário)", en: "Hide phases, set start/end dates (syncs with calendar)" },
  "Operador de Receção": { pt: "Operador de Receção", en: "Reception Operator" },
  "Operador de Transporte": { pt: "Operador de Transporte", en: "Transport Operator" },
  "Operadores": { pt: "Operadores", en: "Operators" },
  "Palavra-passe actual": { pt: "Palavra-passe actual", en: "Current password" },
  "Papel": { pt: "Papel", en: "Role" },
  "Papéis no Processo": { pt: "Papéis no Processo", en: "Roles in the Process" },
  "Perigoso": { pt: "Perigoso", en: "Hazardous" },
  "Período selecionado:": { pt: "Período selecionado:", en: "Selected period:" },
  "Período:": { pt: "Período:", en: "Period:" },
  "Plano/Projeto": { pt: "Plano/Projeto", en: "Plan/Project" },
  "Plataforma de Gestão Ambiental": { pt: "Plataforma de Gestão Ambiental", en: "Environmental Management Platform" },
  "Preenche e submete a ficha semanal com evidências fotográficas e documentais.": { pt: "Preenche e submete a ficha semanal com evidências fotográficas e documentais.", en: "Fills and submits the weekly form with photographic and documentary evidence." },
  "Programa de Monitorização": { pt: "Programa de Monitorização", en: "Monitoring Programme" },
  "Programas e planos do DCAPE — Fase de Construção": { pt: "Programas e planos do DCAPE — Fase de Construção", en: "DCAPE programmes and plans — Construction Phase" },
  "Projetos": { pt: "Projetos", en: "Projects" },
  "Próximo Reporting": { pt: "Próximo Reporting", en: "Next Report" },
  "Próximo reporting": { pt: "Próximo reporting", en: "Next report" },
  "Próximos meses": { pt: "Próximos meses", en: "Coming months" },
  "Pré-visualização do RDCD": { pt: "Pré-visualização do RDCD", en: "RDCD Preview" },
  "Qtd (t)": { pt: "Qtd (t)", en: "Qty (t)" },
  "Quantidade Corrigida (t)": { pt: "Quantidade Corrigida (t)", en: "Corrected Quantity (t)" },
  "Quantidade Original (t)": { pt: "Quantidade Original (t)", en: "Original Quantity (t)" },
  "RAA": { pt: "RAA", en: "RAA" },
  "RAA adiciona comentários com motivo da rejeição": { pt: "RAA adiciona comentários com motivo da rejeição", en: "RAA adds comments with rejection reason" },
  "RAP": { pt: "RAP", en: "RAP" },
  "Rascunho": { pt: "Rascunho", en: "Draft" },
  "Reciclado (t)": { pt: "Reciclado (t)", en: "Recycled (t)" },
  "Recuperar": { pt: "Recuperar", en: "Recover" },
  "Registar Nova e-GAR": { pt: "Registar Nova e-GAR", en: "Register New e-GAR" },
  "Registar e-GAR": { pt: "Registar e-GAR", en: "Register e-GAR" },
  "Resp. Acompanhamento Ambiental": { pt: "Resp. Acompanhamento Ambiental", en: "Environmental Monitoring Officer" },
  "Resp. Acompanhamento do Projeto": { pt: "Resp. Acompanhamento do Projeto", en: "Project Monitoring Officer" },
  "Reveja o resumo antes de gerar o documento Word.": { pt: "Reveja o resumo antes de gerar o documento Word.", en: "Review the summary before generating the Word document." },
  "Reveja, comente e aprove fichas submetidas pelas empresas": { pt: "Reveja, comente e aprove fichas submetidas pelas empresas", en: "Review, comment and approve forms submitted by companies" },
  "Revisão de Fichas": { pt: "Revisão de Fichas", en: "Form Review" },
  "Revê, comenta, aprova ou rejeita as fichas submetidas. Garante conformidade.": { pt: "Revê, comenta, aprova ou rejeita as fichas submetidas. Garante conformidade.", en: "Reviews, comments, approves or rejects submitted forms. Ensures compliance." },
  "Selecionar Projeto(s)": { pt: "Selecionar Projeto(s)", en: "Select Project(s)" },
  "Selecionar Todos": { pt: "Selecionar Todos", en: "Select All" },
  "Selecione os planos a incluir:": { pt: "Selecione os planos a incluir:", en: "Select plans to include:" },
  "Selecione semanas a incluir como evidência:": { pt: "Selecione semanas a incluir como evidência:", en: "Select weeks to include as evidence:" },
  "Selecione um projeto específico no menu lateral para criar uma ficha de controlo.": { pt: "Selecione um projeto específico no menu lateral para criar uma ficha de controlo.", en: "Select a specific project from the sidebar to create a control form." },
  "Selecione um projeto no menu lateral para ver o detalhe completo da timeline.": { pt: "Selecione um projeto no menu lateral para ver o detalhe completo da timeline.", en: "Select a project from the sidebar to see the full timeline detail." },
  "Sem data definida": { pt: "Sem data definida", en: "No date set" },
  "Sem permissão": { pt: "Sem permissão", en: "No permission" },
  "Semana de fim": { pt: "Semana de fim", en: "End week" },
  "Semana de início": { pt: "Semana de início", en: "Start week" },
  "Start Campus": { pt: "Start Campus", en: "Start Campus" },
  "Start Campus — Sines, Portugal": { pt: "Start Campus — Sines, Portugal", en: "Start Campus — Sines, Portugal" },
  "Submeter documento do plano:": { pt: "Submeter documento do plano:", en: "Submit plan document:" },
  "Submetido na plataforma": { pt: "Submetido na plataforma", en: "Submitted on platform" },
  "Supervisiona o processo global, gere fases e define o workflow do projeto.": { pt: "Supervisiona o processo global, gere fases e define o workflow do projeto.", en: "Oversees the overall process, manages phases and defines the project workflow." },
  "Taxa Desvio Aterro": { pt: "Taxa Desvio Aterro", en: "Landfill Diversion Rate" },
  "Todos os projetos": { pt: "Todos os projetos", en: "All projects" },
  "Total": { pt: "Total", en: "Total" },
  "Total Resíduos (t)": { pt: "Total Resíduos (t)", en: "Total Waste (t)" },
  "Trimestre": { pt: "Trimestre", en: "Quarter" },
  "Ver": { pt: "Ver", en: "View" },
  "Verificação de segurança — confirme a sua identidade.": { pt: "Verificação de segurança — confirme a sua identidade.", en: "Security verification — confirm your identity." },
  "Visão geral do estado de cada projeto e a fase em que se encontra.": { pt: "Visão geral do estado de cada projeto e a fase em que se encontra.", en: "Overview of each project's status and current phase." },
  "Volta ao passo 1": { pt: "Volta ao passo 1", en: "Back to step 1" },
  "Volta para Rascunhos": { pt: "Volta para Rascunhos", en: "Back to Drafts" },
  "Último Reporting": { pt: "Último Reporting", en: "Last Report" },
  "Introduza o email associado à sua conta. O administrador será notificado para proceder ao reset da palavra-passe.": { pt: "Introduza o email associado à sua conta. O administrador será notificado para proceder ao reset da palavra-passe.", en: "Enter the email associated with your account. The administrator will be notified to reset your password." },
  "Abra o Google Authenticator ou Microsoft Authenticator e introduza o código de 6 dígitos.": { pt: "Abra o Google Authenticator ou Microsoft Authenticator e introduza o código de 6 dígitos.", en: "Open Google Authenticator or Microsoft Authenticator and enter the 6-digit code." },
  "Rejeitadas": { pt: "Rejeitadas", en: "Rejected" },
  "Entregues": { pt: "Entregues", en: "Delivered" },
  "Técnicos de Ambiente / Total Trabalhadores": { pt: "Técnicos de Ambiente / Total Trabalhadores", en: "Environmental Technicians / Total Workers" },
  "Valores Calculados Automaticamente": { pt: "Valores Calculados Automaticamente", en: "Automatically Calculated Values" },
  "Registo de Incidentes": { pt: "Registo de Incidentes", en: "Incident Log" },
  "Semanas com dados": { pt: "Semanas com dados", en: "Weeks with data" },
  "Nenhum incidente registado": { pt: "Nenhum incidente registado", en: "No incidents registered" },
  "Grau": { pt: "Grau", en: "Severity" },
  "Resolvido": { pt: "Resolvido", en: "Resolved" },
  "Investigação": { pt: "Investigação", en: "Investigation" },
  "Encerrado": { pt: "Encerrado", en: "Closed" },
  "Mensal": { pt: "Mensal", en: "Monthly" },
  "Semestral": { pt: "Semestral", en: "Semi-annual" },
  "Trimestral": { pt: "Trimestral", en: "Quarterly" },
  "Semanal": { pt: "Semanal", en: "Weekly" },
  "HVO": { pt: "HVO", en: "HVO" },
  "Manual": { pt: "Manual", en: "Manual" },
  "Targets": { pt: "Targets", en: "Targets" },
  "Medidas Exploração": { pt: "Medidas Exploração", en: "Operation Measures" },
  "Sem eventos de reporting configurados.": { pt: "Sem eventos de reporting configurados.", en: "No reporting events configured." },
  "Sem e-GARs registadas. Vá ao MIRR para registar.": { pt: "Sem e-GARs registadas. Vá ao MIRR para registar.", en: "No e-GARs registered. Go to MIRR to register." },
  "Total:": { pt: "Total:", en: "Total:" },
  "Desvio aterro:": { pt: "Desvio aterro:", en: "Landfill diversion:" },
  "Sem reportings agendados neste dia.": { pt: "Sem reportings agendados neste dia.", en: "No reports scheduled for this day." },
  "Evento": { pt: "Evento", en: "Event" },
  "Próxima Entrega": { pt: "Próxima Entrega", en: "Next Delivery" },
  "Entidade": { pt: "Entidade", en: "Entity" },
  "Adicionar Novo Evento": { pt: "Adicionar Novo Evento", en: "Add New Event" },
  "Pontual": { pt: "Pontual", en: "One-time" },
  "Próxima Data": { pt: "Próxima Data", en: "Next Date" },
  "Utilizador": { pt: "Utilizador", en: "User" },
  "Detalhes": { pt: "Detalhes", en: "Details" },
  "Sem registos de auditoria.": { pt: "Sem registos de auditoria.", en: "No audit records." },
  "Acesso restrito a administradores e Dono de Obra.": { pt: "Acesso restrito a administradores e Dono de Obra.", en: "Restricted to administrators and Project Owner." },
  "Certificações — SIN01 NEST": { pt: "Certificações — SIN01 NEST", en: "Certifications — SIN01 NEST" },
  "LEED O&M v4.1": { pt: "LEED O&M v4.1", en: "LEED O&M v4.1" },
  "EED — Centros de Dados": { pt: "EED — Centros de Dados", en: "EED — Data Centers" },
  "CELE — EU ETS": { pt: "CELE — EU ETS", en: "CELE — EU ETS" },
  "Instalações com TEGEE": { pt: "Instalações com TEGEE", en: "Facilities with TEGEE" },
  "GAMMA — Sustentabilidade Comunitária": { pt: "GAMMA — Sustentabilidade Comunitária", en: "GAMMA — Community Sustainability" },
  "Programa de apoio a projetos comunitários": { pt: "Programa de apoio a projetos comunitários", en: "Community project support programme" },
  "Criar Nova Edição": { pt: "Criar Nova Edição", en: "Create New Edition" },
  "A nova edição será criada com os pilares e critérios padrão. Pode editá-los depois na tab Definições.": { pt: "A nova edição será criada com os pilares e critérios padrão. Pode editá-los depois na tab Definições.", en: "The new edition will be created with default pillars and criteria. You can edit them later in the Settings tab." },
  "Cole o URL e ajuste a posição vertical. Use imagens de": { pt: "Cole o URL e ajuste a posição vertical. Use imagens de", en: "Paste the URL and adjust the vertical position. Use images from" },
  "Nova localização de imagem": { pt: "Nova localização de imagem", en: "New image location" },
  "Página onde inserir": { pt: "Página onde inserir", en: "Page to insert" },
  "Dica:": { pt: "Dica:", en: "Tip:" },
  "Periodicidade": { pt: "Periodicidade", en: "Frequency" },
};

interface LanguageContextType {
  language: Lang;
  setLanguage: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "pt",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Lang>(() =>
    (localStorage.getItem("app_lang") as Lang) || "pt"
  );

  useEffect(() => {
    localStorage.setItem("app_lang", language);
  }, [language]);

  const t = (key: string): string => {
    const entry = translations[key];
    if (!entry) return key;
    return entry[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export default LanguageContext;
